### ISSUE TITLE
Error: AttributeError: module 'xumm' has no attribute 'XummSdk'

### ISSUE THREAD

**Issue by NeoSephiroth** [XRPL-Labs/xumm-sdk-py#31]
Using python 3.9 I get this error

I entered correctly my API keys

**Comment by dangell7** [comment]
Can you post an example of your code?

**Comment by dangell7** [comment]
I've figured it out. When you create files and folders you have to be really careful not to name the file or the folder the same name as the repository. 

In your case the file name is xumm.py and the repo is xumm. 

Change the name of the file to something a bit more abstract and it should work.
